### ISSUE TITLE
Apache Cordova 

### ISSUE THREAD

**Issue by nscarg** [Saulis/iron-data-table#53] opened 2016-04-28 21:16 UTC
I have an application on polymer plataform , but for operational reasons, need to run plenty cellular and tables telephones , for which migrate over cordova apache, the problem that arises is that when I run emulating a cell the compononente not work for me without shed any error.
If I run the same application without touching any code emulating a browser works perfectly , you could guide me to solve the problem in advance thank you very much .

**Comment by Saulis** [comment] 2016-04-29 05:16
I'd be more than happy to help you out!

Might be best to exchange ideas in the [Gitter chat](https://gitter.im/Saulis/iron-data-table?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by nscarg** [comment] 2016-05-02 15:32
Before starting thank you very much for your attention , I happened to comment on apache cordova have problems , but not on the browser that works perfectly as you comment .
1) The filter and sort not work for me .
2) If the title frame check mark me all this is ok , but not brand me individually

Again many thanks for your time

Attach the file
[nsc-msgview.zip](https://github.com/Saulis/iron-data-table/files/245360/nsc-msgview.zip)

**Comment by Saulis** [comment] 2016-05-23 07:37
Hi!

I'm not entirely sure I understand what the problem is, but I added a simple example here how to do filtering with an external filter input: http://jsbin.com/facabu/edit?html,output

For the multi-selection, it works only on Chrome currently, there's a bug issued here: #63

**Comment by Saulis** [comment] 2016-06-07 20:33
@nscarg did you get everything working or is there still something?

**Comment by Saulis** [comment] 2016-06-20 05:08
OK, I'm going to close this issue now, but please reopen or comment if there is some new information on this.

**Closed as completed by Saulis** 2016-06-20 05:08 UTC
